# Identifiers & Paths
batch_id: "TEST_RUN"
fastq_dir: ""
manifest: ""
batch_out: ""

# Toggles
run_fastqc: true

# References
references:
  fasta: "/global/project/hpcg6049/somatic_pipeline/data/references/GRCh38.d1.vd1.fa"
  bwamem2_idx: "/global/project/hpcg6049/somatic_pipeline/data/references/GRCh38.d1.vd1.fa"
  
  # --- NEW: Germline Resource for Contamination ---
  # Must have AF (Allele Frequency) in INFO field.
  # Using your prepared 1000G file as a safe fallback.
  germline: "/global/project/hpcg6049/somatic_pipeline/data/references/prepared_known_sites/1kg.indels.d1vd1.ready.vcf.gz"

  known_sites:
    mills: "/global/project/hpcg6049/somatic_pipeline/data/references/prepared_known_sites/Mills.d1vd1.ready.vcf.gz"
    kg_indels: "/global/project/hpcg6049/somatic_pipeline/data/references/prepared_known_sites/1kg.indels.d1vd1.ready.vcf.gz"
    dbsnp: "/global/project/hpcg6049/somatic_pipeline/data/references/prepared_known_sites/dbsnp.gcf40.d1vd1.ready.vcf.gz"

# Containers (Absolute Paths)
containers:
  tidyverse: "/global/project/hpcg6049/somatic_pipeline/containers/NXF_SINGULARITY_CACHEDIR/tidyverse_4.5.1.sif"
  fastp: "/global/project/hpcg6049/somatic_pipeline/containers/NXF_SINGULARITY_CACHEDIR/fastp-1.0.1--heae3180_0.sif"
  fastqc: "/global/project/hpcg6049/somatic_pipeline/containers/NXF_SINGULARITY_CACHEDIR/fastqc-0.12.1--hdfd78af_0.sif"
  gatk: "/global/project/hpcg6049/somatic_pipeline/containers/NXF_SINGULARITY_CACHEDIR/gatk4-4.6.2.0--py310hdfd78af_1.sif"
  samtools: "/global/project/hpcg6049/somatic_pipeline/containers/NXF_SINGULARITY_CACHEDIR/samtools-1.22.1--h96c455f_0.sif"
  bwamem2: "/global/project/hpcg6049/somatic_pipeline/containers/NXF_SINGULARITY_CACHEDIR/bwa-0.7.18--h577a1d6_2.sif"

# Resources (Minutes and MB)
resources:
  merge:
    mem_mb: 32000
    runtime: 240
    cpus: 8
  fastp:
    mem_mb: 16000
    runtime: 720
    cpus: 16
  fastqc:
    mem_mb: 8000
    runtime: 240
    cpus: 4
  align:
    mem_mb: 180000
    runtime: 2880
    cpus: 32
  markdup:
    mem_mb: 180000
    runtime: 1440
    cpus: 8
  bqsr:
    mem_mb: 180000
    runtime: 1440
    cpus: 8
  flagstat:
    mem_mb: 8000
    runtime: 240
    cpus: 2
  wgsmetrics:
    mem_mb: 64000
    runtime: 1440
    cpus: 8
  mutect2:
    mem_mb: 64000
    runtime: 1440
    cpus: 16
